name: publish

on: 
  workflow_dispatch:
    inputs:
        name:
          description: 'Name of user requesting job'     
          required: true
          default: 'Sync Health CI'
        email:
          description: 'Email address of user requesting job'     
          required: true
          default: 'ci@sync.health'
        message:
          description: 'Commit message'  
          required: true
          default: 'publish from Sync Studio'
        env:
          description: 'Environment staging or production'  
          required: true
          default: 'staging'

jobs:
  publish_job:
    runs-on: ubuntu-latest
    name: Publish latest content from sharepoint
    env:
      MSGRAPH_TENANT: ${{ secrets.MSGRAPH_TENANT }}
      MSGRAPH_CLIENT_ID: ${{ secrets.MSGRAPH_CLIENT_ID }}
      MSGRAPH_SECRET: ${{ secrets.MSGRAPH_SECRET }}
      BERUN_ALGOLIA_APIADMIN: ${{ secrets.BERUN_ALGOLIA_APIADMIN }}
      BERUN_ALGOLIA_APPID: ${{ secrets.BERUN_ALGOLIA_APPID }}
      BERUN_ALGOLIA_APIKEY: ${{ secrets.BERUN_ALGOLIA_APIKEY }}
      BERUN_ALGOLIA_INDEX: ${{ secrets.BERUN_ALGOLIA_INDEX }}
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      USER_EMAIL: ${{ github.event.inputs.email }}
      USER_NAME: ${{ github.event.inputs.name }}
      MESSAGE: ${{ github.event.inputs.message }}
    steps:
    - uses: actions/checkout@v2
    - uses: synchealthlabs/github-action-teams@main
      with:
        github-token: ${{ github.token }}
        webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
        position: start
    - uses: actions/setup-node@v1
      with:
        node-version: '12'
    - run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.NPM_SH_TOKEN }}" > ~/.npmrc
    - run: yarn
    - run: npm run download-ci
    - run: npm run build-ci
    - run: npm run deploy-prod
    - uses: synchealthlabs/github-action-teams@main
      if: always() # to let this step always run even if previous step(s) failed
      with:
        github-token: ${{ github.token }}
        webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
        position: finish